version: '3'

volumes:
    ppc_db: 

services:    
    vue-app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: vue-app        
        ports:
            - "${PORT}:${PORT}"
        environment:            
            - PORT=${PORT}          
        command: /bin/sh -c "npm run build && http-server dist"
        
    vue-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: vue-api
        volumes: 
            - ppc_db:/app/database        
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            - API_PORT=${API_PORT}
        command: "npm run start"
